import type { Store, Category, CatalogProduct, StoreProduct, Vendor } from "./types"

/**
 * 샘플 데이터 (인메모리)
 *
 * 실제 DB 연동 시 이 파일은 테이블 시드 데이터에 해당합니다.
 * lib/queries.ts 의 함수들만 실제 SQL 쿼리로 교체하면 됩니다.
 */

/* ----------------------------- 카테고리 ----------------------------- */
export const categories: Category[] = [
  { id: "cat-ramen", name: "라면", nameHu: "Ramen", nameEn: "Ramen", icon: "soup" },
  { id: "cat-frozen", name: "냉동식품", nameHu: "Fagyasztott", nameEn: "Frozen", icon: "snowflake" },
  { id: "cat-sauce", name: "소스/장류", nameHu: "Szószok", nameEn: "Sauces", icon: "milk" },
  { id: "cat-snack", name: "과자", nameHu: "Snack", nameEn: "Snacks", icon: "cookie" },
  { id: "cat-drink", name: "음료", nameHu: "Italok", nameEn: "Drinks", icon: "cup-soda" },
  { id: "cat-fresh", name: "신선/채소", nameHu: "Friss", nameEn: "Fresh", icon: "carrot" },
  { id: "cat-banchan", name: "김치/반찬", nameHu: "Kimchi", nameEn: "Kimchi", icon: "salad" },
  { id: "cat-rice", name: "쌀/면", nameHu: "Rizs/Tészta", nameEn: "Rice/Noodles", icon: "wheat" },
]

/* ------------------------------- 마트 ------------------------------- */
export const stores: Store[] = [
  {
    id: "store-seoul",
    slug: "seoul-mart",
    name: "서울마트",
    nameHu: "Seoul Mart",
    nameEn: "Seoul Mart",
    logo: "/stores/seoul-mart-logo.png",
    coverImage: "/stores/seoul-mart-cover.png",
    description: "부다페스트 최대 한인 식료품점. 신선 채소와 반찬이 매일 입고됩니다.",
    descriptionHu: "Budapest legnagyobb koreai élelmiszerboltja. Friss zöldségek és köretek naponta érkeznek.",
    descriptionEn: "Budapest's largest Korean grocery. Fresh vegetables and side dishes arrive daily.",
    district: "VI. kerület",
    address: "Andrássy út 12, 1061 Budapest",
    deliveryFee: 990,
    minOrder: 5000,
    deliveryTimeMin: 35,
    rating: 4.8,
    ratingCount: 1240,
    isOpen: true,
    tags: ["한식", "신선식품", "반찬"],
  },
  {
    id: "store-kfood",
    slug: "k-food-house",
    name: "K푸드하우스",
    nameHu: "K-Food House",
    nameEn: "K-Food House",
    logo: "/stores/kfood-logo.png",
    coverImage: "/stores/kfood-cover.png",
    description: "라면과 간편식이 강점인 아시안 마트. 늦은 밤까지 배달됩니다.",
    descriptionHu: "Ramenben és készételekben erős ázsiai bolt. Késő éjszakáig szállít.",
    descriptionEn: "An Asian mart strong in ramen and ready meals. Delivers late into the night.",
    district: "VII. kerület",
    address: "Király utca 45, 1077 Budapest",
    deliveryFee: 690,
    minOrder: 4000,
    deliveryTimeMin: 25,
    rating: 4.6,
    ratingCount: 856,
    isOpen: true,
    tags: ["라면", "간편식", "야간배달"],
  },
  {
    id: "store-asiacenter",
    slug: "asia-center-mart",
    name: "아시아센터마트",
    nameHu: "Asia Center Mart",
    nameEn: "Asia Center Mart",
    logo: "/stores/asia-center-logo.png",
    coverImage: "/stores/asia-center-cover.png",
    description: "한중일 식자재를 한 곳에서. 대용량 상품이 저렴합니다.",
    descriptionHu: "Koreai, kínai és japán alapanyagok egy helyen. Kedvező árak nagy kiszerelésben.",
    descriptionEn: "Korean, Chinese and Japanese groceries in one place. Great prices on bulk items.",
    district: "X. kerület",
    address: "Kőbányai út 21, 1101 Budapest",
    deliveryFee: 1290,
    minOrder: 6000,
    deliveryTimeMin: 45,
    rating: 4.4,
    ratingCount: 512,
    isOpen: true,
    tags: ["대용량", "아시안", "저가"],
  },
  {
    id: "store-hansung",
    slug: "hansung-food",
    name: "한성식품",
    nameHu: "Hansung Food",
    nameEn: "Hansung Food",
    logo: "/stores/hansung-logo.png",
    coverImage: "/stores/hansung-cover.png",
    description: "정통 김치와 젓갈, 장류 전문. 직접 담근 반찬이 인기입니다.",
    descriptionHu: "Hagyományos kimchi, sózott tenger gyümölcsei és szószok szakértője. A házi köretek népszerűek.",
    descriptionEn: "Specializing in authentic kimchi, salted seafood and pastes. Homemade side dishes are popular.",
    district: "XIII. kerület",
    address: "Váci út 78, 1133 Budapest",
    deliveryFee: 890,
    minOrder: 5000,
    deliveryTimeMin: 40,
    rating: 4.9,
    ratingCount: 674,
    isOpen: false,
    tags: ["김치", "장류", "수제반찬"],
  },
  {
    id: "store-tokyo",
    slug: "tokyo-market",
    name: "도쿄마켓",
    nameHu: "Tokyo Market",
    nameEn: "Tokyo Market",
    logo: "/stores/tokyo-logo.png",
    coverImage: "/stores/tokyo-cover.png",
    description: "일본 식자재 중심이지만 한국 인기 상품도 함께 취급합니다.",
    descriptionHu: "Japán alapanyagokra összpontosít, de népszerű koreai termékeket is árul.",
    descriptionEn: "Focused on Japanese groceries but also carries popular Korean products.",
    district: "V. kerület",
    address: "Bajcsy-Zsilinszky út 5, 1051 Budapest",
    deliveryFee: 1090,
    minOrder: 4500,
    deliveryTimeMin: 30,
    rating: 4.5,
    ratingCount: 389,
    isOpen: true,
    tags: ["일식", "아시안", "인기상품"],
  },
]

/* --------------------------- 마스터 상품 --------------------------- */
export const catalogProducts: CatalogProduct[] = [
  // 라면
  {
    id: "p-shin",
    nameKo: "신라면 (5개입)",
    nameHu: "Shin Ramyun (5 db)",
    nameEn: "Shin Ramyun (5 pack)",
    description: "얼큰한 국물의 대표 한국 라면",
    descriptionHu: "Korea ikonikus, csípős levesű ramenje",
    descriptionEn: "Korea's iconic spicy-broth ramen",
    imageUrl: "/products/shin-ramyun.png",
    categoryId: "cat-ramen",
    unit: "120g x 5",
    brand: "농심",
  },
  {
    id: "p-jin",
    nameKo: "진라면 매운맛 (5개입)",
    nameHu: "Jin Ramen Spicy (5 db)",
    nameEn: "Jin Ramen Spicy (5 pack)",
    description: "깊고 진한 매운맛 라면",
    descriptionHu: "Mély, gazdag és csípős ramen",
    descriptionEn: "Deep, rich and spicy ramen",
    imageUrl: "/products/jin-ramen.png",
    categoryId: "cat-ramen",
    unit: "120g x 5",
    brand: "오뚜기",
  },
  {
    id: "p-buldak",
    nameKo: "불닭볶음면",
    nameHu: "Buldak Csípős",
    nameEn: "Buldak Spicy Noodles",
    description: "화끈한 매운 볶음면",
    descriptionHu: "Tüzesen csípős sült tészta",
    descriptionEn: "Fiery hot stir-fried noodles",
    imageUrl: "/products/buldak.png",
    categoryId: "cat-ramen",
    unit: "140g",
    brand: "삼양",
  },
  // 냉동식품
  {
    id: "p-mandu",
    nameKo: "비비고 왕교자 만두",
    nameHu: "Bibigo Mandu",
    nameEn: "Bibigo Dumplings",
    description: "고기와 채소가 가득한 냉동 만두",
    descriptionHu: "Hússal és zöldséggel teli fagyasztott gombóc",
    descriptionEn: "Frozen dumplings full of meat and vegetables",
    imageUrl: "/products/mandu.png",
    categoryId: "cat-frozen",
    unit: "525g",
    brand: "CJ",
  },
  {
    id: "p-tteok",
    nameKo: "떡볶이 떡",
    nameHu: "Tteokbokki rizssütemény",
    nameEn: "Tteokbokki Rice Cakes",
    description: "쫄깃한 떡볶이용 가래떡",
    descriptionHu: "Rágós rizssütemény tteokbokkihoz",
    descriptionEn: "Chewy rice cakes for tteokbokki",
    imageUrl: "/products/tteok.png",
    categoryId: "cat-frozen",
    unit: "1kg",
    brand: "대상",
  },
  // 소스/장류
  {
    id: "p-gochujang",
    nameKo: "고추장",
    nameHu: "Gochujang",
    nameEn: "Gochujang (Chili Paste)",
    description: "매콤달콤한 발효 고추장",
    descriptionHu: "Édes-csípős, erjesztett chilipaszta",
    descriptionEn: "Sweet and spicy fermented chili paste",
    imageUrl: "/products/gochujang.png",
    categoryId: "cat-sauce",
    unit: "500g",
    brand: "해찬들",
  },
  {
    id: "p-doenjang",
    nameKo: "된장",
    nameHu: "Doenjang",
    nameEn: "Doenjang (Soybean Paste)",
    description: "구수한 재래식 된장",
    descriptionHu: "Ízletes, hagyományos szójababpaszta",
    descriptionEn: "Savory traditional soybean paste",
    imageUrl: "/products/doenjang.png",
    categoryId: "cat-sauce",
    unit: "500g",
    brand: "해찬들",
  },
  {
    id: "p-soysauce",
    nameKo: "양조간장",
    nameHu: "Szójaszósz",
    nameEn: "Soy Sauce",
    description: "감칠맛 좋은 양조간장",
    descriptionHu: "Gazdag, umami ízű szójaszósz",
    descriptionEn: "Rich umami brewed soy sauce",
    imageUrl: "/products/soy-sauce.png",
    categoryId: "cat-sauce",
    unit: "1L",
    brand: "샘표",
  },
  // 과자
  {
    id: "p-choco",
    nameKo: "초코파이 (12개입)",
    nameHu: "Choco Pie (12 db)",
    nameEn: "Choco Pie (12 pack)",
    description: "부드러운 마시멜로 초코파이",
    descriptionHu: "Puha mályvacukros csokipite",
    descriptionEn: "Soft marshmallow choco pie",
    imageUrl: "/products/choco-pie.png",
    categoryId: "cat-snack",
    unit: "39g x 12",
    brand: "오리온",
  },
  {
    id: "p-shrimp",
    nameKo: "새우깡",
    nameHu: "Saewookkang",
    nameEn: "Shrimp Crackers",
    description: "고소한 새우맛 과자",
    descriptionHu: "Ízletes, garnélás rágcsálnivaló",
    descriptionEn: "Savory shrimp-flavored snack",
    imageUrl: "/products/saewookkang.png",
    categoryId: "cat-snack",
    unit: "90g",
    brand: "농심",
  },
  // 음료
  {
    id: "p-sikhye",
    nameKo: "식혜",
    nameHu: "Sikhye rizsital",
    nameEn: "Sikhye Rice Drink",
    description: "달콤한 전통 쌀 음료",
    descriptionHu: "Édes, hagyományos rizsital",
    descriptionEn: "Sweet traditional rice drink",
    imageUrl: "/products/sikhye.png",
    categoryId: "cat-drink",
    unit: "500ml",
    brand: "비락",
  },
  {
    id: "p-banana",
    nameKo: "바나나맛 우유",
    nameHu: "Banán tej",
    nameEn: "Banana Milk",
    description: "국민 바나나맛 우유",
    descriptionHu: "Korea kedvenc banántej itala",
    descriptionEn: "Korea's beloved banana milk",
    imageUrl: "/products/banana-milk.png",
    categoryId: "cat-drink",
    unit: "240ml",
    brand: "빙그레",
  },
  // 신선/채소
  {
    id: "p-napa",
    nameKo: "배추 (1포기)",
    nameHu: "Kínai kel (1 fej)",
    nameEn: "Napa Cabbage (1 head)",
    description: "김치용 신선한 배추",
    descriptionHu: "Friss kínai kel kimchihez",
    descriptionEn: "Fresh napa cabbage for kimchi",
    imageUrl: "/products/napa-cabbage.png",
    categoryId: "cat-fresh",
    unit: "약 2kg",
    brand: "산지직송",
  },
  {
    id: "p-radish",
    nameKo: "무 (1개)",
    nameHu: "Retek (1 db)",
    nameEn: "Korean Radish (1 pc)",
    description: "국물용 신선한 무",
    descriptionHu: "Friss retek levesekhez",
    descriptionEn: "Fresh radish for soups",
    imageUrl: "/products/radish.png",
    categoryId: "cat-fresh",
    unit: "약 1kg",
    brand: "산지직송",
  },
  // 김치/반찬
  {
    id: "p-kimchi",
    nameKo: "포기김치",
    nameHu: "Poggi Kimchi",
    nameEn: "Whole Cabbage Kimchi",
    description: "잘 익은 배추 포기김치",
    descriptionHu: "Jól érlelt egész káposztás kimchi",
    descriptionEn: "Well-fermented whole cabbage kimchi",
    imageUrl: "/products/kimchi.png",
    categoryId: "cat-banchan",
    unit: "1kg",
    brand: "종가집",
  },
  {
    id: "p-myeolchi",
    nameKo: "멸치볶음",
    nameHu: "Szárított hal",
    nameEn: "Stir-fried Anchovies",
    description: "짭조름한 밑반찬 멸치볶음",
    descriptionHu: "Sós, sült szardella köret",
    descriptionEn: "Savory stir-fried anchovy side dish",
    imageUrl: "/products/myeolchi.png",
    categoryId: "cat-banchan",
    unit: "200g",
    brand: "수제반찬",
  },
  // 쌀/면
  {
    id: "p-rice",
    nameKo: "햇반 (12개입)",
    nameHu: "Instant rizs (12 db)",
    nameEn: "Instant Rice (12 pack)",
    description: "간편하게 즐기는 즉석밥",
    descriptionHu: "Kényelmes instant főtt rizs",
    descriptionEn: "Convenient instant cooked rice",
    imageUrl: "/products/hetban.png",
    categoryId: "cat-rice",
    unit: "210g x 12",
    brand: "CJ",
  },
  {
    id: "p-noodle",
    nameKo: "소면",
    nameHu: "Somyeon tészta",
    nameEn: "Somyeon Thin Noodles",
    description: "잔치국수용 가는 소면",
    descriptionHu: "Vékony tészta ünnepi leveshez",
    descriptionEn: "Thin noodles for banquet noodle soup",
    imageUrl: "/products/somyeon.png",
    categoryId: "cat-rice",
    unit: "900g",
    brand: "풀무원",
  },
]

/* ----------------- 마트별 판매 상품 (가격 리스팅) ----------------- */
/**
 * 여기서 마트별 가격 차이가 만들어집니다.
 * 예: 신라면(p-shin)을 서울마트는 3990Ft, K푸드하우스는 3690Ft, 아시아센터는 3490Ft에 판매.
 */
let sp = 0
const listing = (
  storeId: string,
  catalogProductId: string,
  price: number,
  opts?: { inStock?: boolean; isFeatured?: boolean },
): StoreProduct => ({
  id: `sp-${++sp}`,
  storeId,
  catalogProductId,
  price,
  inStock: opts?.inStock ?? true,
  isFeatured: opts?.isFeatured ?? false,
})

export const storeProducts: StoreProduct[] = [
  /* 서울마트 — 신선/반찬 강점, 가격은 중상 */
  listing("store-seoul", "p-shin", 3990, { isFeatured: true }),
  listing("store-seoul", "p-jin", 3790),
  listing("store-seoul", "p-buldak", 990, { isFeatured: true }),
  listing("store-seoul", "p-mandu", 2490),
  listing("store-seoul", "p-tteok", 1890),
  listing("store-seoul", "p-gochujang", 2290),
  listing("store-seoul", "p-doenjang", 2190),
  listing("store-seoul", "p-choco", 2990),
  listing("store-seoul", "p-banana", 690),
  listing("store-seoul", "p-napa", 1490, { isFeatured: true }),
  listing("store-seoul", "p-radish", 890),
  listing("store-seoul", "p-kimchi", 3490, { isFeatured: true }),
  listing("store-seoul", "p-myeolchi", 2790),
  listing("store-seoul", "p-rice", 4990),

  /* K푸드하우스 — 라면/간편식 저렴, 신선식품 없음 */
  listing("store-kfood", "p-shin", 3690, { isFeatured: true }),
  listing("store-kfood", "p-jin", 3490),
  listing("store-kfood", "p-buldak", 890, { isFeatured: true }),
  listing("store-kfood", "p-mandu", 2690),
  listing("store-kfood", "p-tteok", 1990),
  listing("store-kfood", "p-choco", 2790),
  listing("store-kfood", "p-shrimp", 990),
  listing("store-kfood", "p-sikhye", 790),
  listing("store-kfood", "p-banana", 650, { isFeatured: true }),
  listing("store-kfood", "p-rice", 4790),
  listing("store-kfood", "p-noodle", 1490),

  /* 아시아센터마트 — 대용량/최저가 */
  listing("store-asiacenter", "p-shin", 3490, { isFeatured: true }),
  listing("store-asiacenter", "p-jin", 3290, { isFeatured: true }),
  listing("store-asiacenter", "p-buldak", 850),
  listing("store-asiacenter", "p-mandu", 2290, { isFeatured: true }),
  listing("store-asiacenter", "p-gochujang", 1990),
  listing("store-asiacenter", "p-doenjang", 1890),
  listing("store-asiacenter", "p-soysauce", 1690),
  listing("store-asiacenter", "p-shrimp", 890),
  listing("store-asiacenter", "p-rice", 4490, { isFeatured: true }),
  listing("store-asiacenter", "p-noodle", 1290),
  listing("store-asiacenter", "p-choco", 2690),

  /* 한성식품 — 김치/장류 전문 (현재 영업종료 상태) */
  listing("store-hansung", "p-kimchi", 3290, { isFeatured: true }),
  listing("store-hansung", "p-gochujang", 2190),
  listing("store-hansung", "p-doenjang", 2090),
  listing("store-hansung", "p-soysauce", 1890),
  listing("store-hansung", "p-myeolchi", 2590, { isFeatured: true }),
  listing("store-hansung", "p-napa", 1390),
  listing("store-hansung", "p-radish", 790),
  listing("store-hansung", "p-shin", 4190),

  /* 도쿄마켓 — 일식 중심, 한국 인기상품 일부 (프리미엄 가격) */
  listing("store-tokyo", "p-shin", 4090),
  listing("store-tokyo", "p-buldak", 1090, { isFeatured: true }),
  listing("store-tokyo", "p-mandu", 2790),
  listing("store-tokyo", "p-soysauce", 1990, { isFeatured: true }),
  listing("store-tokyo", "p-choco", 3190),
  listing("store-tokyo", "p-shrimp", 1090),
  listing("store-tokyo", "p-banana", 750),
  listing("store-tokyo", "p-sikhye", 890),
  listing("store-tokyo", "p-noodle", 1590),
  listing("store-tokyo", "p-rice", 5190, { inStock: false }),
]

/* ---------------------- 입점업체(벤더) 계정 ---------------------- */
export const vendors: Vendor[] = [
  { id: "v-1", name: "김서울", nameEn: "Kim Seoul", email: "owner@seoulmart.hu", storeId: "store-seoul" },
  { id: "v-2", name: "이케이", nameEn: "Lee K", email: "owner@kfoodhouse.hu", storeId: "store-kfood" },
  { id: "v-3", name: "박아시아", nameEn: "Park Asia", email: "owner@asiacenter.hu", storeId: "store-asiacenter" },
  { id: "v-4", name: "최한성", nameEn: "Choi Hansung", email: "owner@hansung.hu", storeId: "store-hansung" },
  { id: "v-5", name: "정도쿄", nameEn: "Jung Tokyo", email: "owner@tokyomarket.hu", storeId: "store-tokyo" },
]
